### ISSUE TITLE
Has no setup.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mousadialo/django-profile#74]
```
What steps will reproduce the problem?
1. Add 'django-profile' to your own packages list of dependencies
2. Run setup.py build
3. Be sad

What is the expected output? What do you see instead?
Expected: Smiles
Actual: Frowns

setup.py is added below. There is currently a bug in PIL that causes an 
easy_install'd version of it to work improperly. I have also added a 
MANIFEST.in that should _not_ be necessary because django-profile uses SVN. 
But just in case package data is not being included, this file should be 
added to the root directory.

The command `wget http://python-distribute.org/distribute_setup.py` should 
also be run :)
```

Original issue reported on code.google.com by `abhishek.mukher.g` on 22 Nov 2009 at 1:07

Attachments:
- [MANIFEST.in](https://storage.googleapis.com/google-code-attachments/django-profile/issue-74/comment-0/MANIFEST.in)
- [setup.py](https://storage.googleapis.com/google-code-attachments/django-profile/issue-74/comment-0/setup.py)

**Comment by GoogleCodeExporter** [comment]
```
The URL got mangled for distribute setup, here's a fixed command:

  wget http://python-distribute.org/distribute_setup.py
```

Original comment by `abhishek.mukher.g` on 22 Nov 2009 at 1:09

**Comment by GoogleCodeExporter** [comment]
```
I'm apparently mistaken. However, the tarballs in the download page do not have 
a 
setup.py and django-profile is not in pypi. Could either of these two be done 
to make 
it easier to add django-profile to our own setup.py
```

Original comment by `abhishek.mukher.g` on 22 Nov 2009 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
A setup.py is also required for using pip freeze/install

andre@localhost djcode $ pip install 
http://django-profile.googlecode.com/files/django-profile-0.6.tgz
Downloading/unpacking 
http://django-profile.googlecode.com/files/django-profile-0.6.tgz
  Downloading django-profile-0.6.tgz (137Kb): 137Kb downloaded
  Running setup.py egg_info for package from http://django-profile.googlecode.com/files/django-profile-0.6.tgz
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-fkTZ6T-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-fkTZ6T-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/andre/.pip/pip.log
andre@localhost djcode $ ls /tmp/pip-fkTZ6T-build/
CHANGELOG.txt  demo  INSTALL.txt  LICENSE.txt  media  pip-egg-info  README.txt  
TODO.txt  userprofile
andre@localhost djcode $
```

Original comment by `andre.mi...@gmail.com` on 3 Sep 2010 at 2:42
